#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-qed
Version  : 2.9.2
Release  : 5
URL      : https://rubygems.org/downloads/qed-2.9.2.gem
Source0  : https://rubygems.org/downloads/qed-2.9.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-qed-bin
BuildRequires : ruby
BuildRequires : rubygem-ae
BuildRequires : rubygem-ansi
BuildRequires : rubygem-brass
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rulebow

%description
# Ruby Q.E.D.
[Homepage](http://rubyworks.github.com/qed) /
[Documentation](http://rubydoc.info/gems/qed/frames) /
[Report Issue](http://github.com/rubyworks/qed/issues) /
[Development](http://github.com/rubyworks/qed) /
[Mailing list](http://groups.google.com/group/rubyworks-mailinglist) &nbsp; &nbsp;
[![Build Status](https://secure.travis-ci.org/rubyworks/qed.png)](http://travis-ci.org/rubyworks/qed)
[![Gem Version](https://badge.fury.io/rb/qed.png)](http://badge.fury.io/rb/qed)

%package bin
Summary: bin components for the rubygem-qed package.
Group: Binaries

%description bin
bin components for the rubygem-qed package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n qed-2.9.2
gem spec %{SOURCE0} -l --ruby > rubygem-qed.gemspec

%build
gem build rubygem-qed.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
qed-2.9.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/qed-2.9.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/.index
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/bin/qed
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/bin/qedoc
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/01_demos.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/02_advice.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/03_helpers.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/04_samples.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/05_quote.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/07_toplevel.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/08_cross_script.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/09_cross_script.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/10_constant_lookup.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/11_embedded_rules.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/99_issues/02_topcode.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/ae.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/constant.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/fileutils.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/markup.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/quote.md
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/applique/toplevel.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/helpers/advice.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/helpers/toplevel.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/samples/data.txt
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/demo/samples/table.yml
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed.yml
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/applique.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/cli/qed.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/cli/qedoc.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/configure.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/demo.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/document/jquery.js
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/document/markup.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/document/template.rhtml
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/evaluator.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/helpers/file_fixtures.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/helpers/shell_session.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/qparser.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/reporter/abstract.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/reporter/dotprogress.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/reporter/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/reporter/linear.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/reporter/tapy.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/reporter/verbatim.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/scope.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/session.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/settings.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/step.rb
/usr/lib64/ruby/gems/2.3.0/gems/qed-2.9.2/lib/qed/utils.rb
/usr/lib64/ruby/gems/2.3.0/specifications/qed-2.9.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/qed
/usr/bin/qedoc
